version: '3.4'

services:
    wave:
        image: ${DOCKER_REGISTRY-}wave
        build:
            context: .
            dockerfile: Wave/Dockerfile   
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2017-CU21-ubuntu-16.04"
        environment:
            SA_PASSWORD: "nagyonerospassword"
            ACCEPT_EULA: "Y"