version: '3.4'

services:
    db:
        image: "mcr.microsoft.com/mssql/server:2017-CU21-ubuntu-16.04"
        environment:
            SA_PASSWORD: "1Secure*Password1"
            ACCEPT_EULA: "Y"
    blob:
        image: "mcr.microsoft.com/azure-storage/azurite:3.9.0"
    wave:
        image: ${DOCKER_REGISTRY-}wave
        build:
            context: .
            dockerfile: Wave/Dockerfile 
        depends_on:
            - db
            - blob
        environment:
            CONNECTIONSTRINGS__DEFAULTCONNECTION: "Server=db;Database=wave;User=sa;Password=1Secure*Password1;"
            AUTH0APICONFIG__AUTHORITY: "https://banyi97.eu.auth0.com/"
            AUTH0APICONFIG__IDENTIFIER: "https://waveapi"
            AUTH0APICONFIG__CLIENTID: "JPZQiLb9tdI3mZLnOOr3Aa21IkwwBU7v"
            AUTH0APICONFIG__CLIENTSECRET: "1f1em3LXDEpILszfKOjdMeqp4TBfWEsMj4__rfYR_CZ2HhpEx7FofvqxwYAVIW2n"
            AUTH0APICONFIG__DOMAIN: "banyi97.eu.auth0.com"
            AZUREBLOBCONFIG__CONNECTIONSTRING: "AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=blob:10000/devstoreaccount1;"
            AZUREBLOBCONFIG__CONTAINERTRACK: "wavetrack"
            AZUREBLOBCONFIG__CONTAINERIMG: "waveimg"
